/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 duck.gltf --transform 
Files: duck.gltf [170.67KB] > /Users/kellyhuang/Documents/cute_chick/duck-transformed.glb [117.47KB] (31%)
Author: iclartworks (https://sketchfab.com/iclartworks)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-chick-623cc9c755b0417f920037866065efcb
Title: Cute Chick
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/duck-transformed.glb')
  const { actions } = useAnimations(animations, group)
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="Cube002_2" position={[-0.039, 0.57, 0.214]} rotation={[-0.707, 0, 0]} scale={[0.27, 0.198, 0.234]}>
            <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube003_3" position={[-0.133, -0.457, -0.018]} rotation={[0, -0.006, 0]} scale={[0.191, 0.076, 0.172]}>
            <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube005_4" position={[0.836, 1.211, -0.019]} rotation={[-Math.PI, 0, 2.727]} scale={[-0.119, -0.071, -0.139]}>
            <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube006_5" position={[0.836, 1.211, -0.019]} rotation={[3.114, -0.001, -2.705]} scale={[-0.119, -0.071, -0.139]}>
            <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube010_14" position={[0, 1.327, 0]} rotation={[0.052, 0.029, 0.214]}>
            <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.PaletteMaterial002} />
          </group>
        </group>
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[0, 0.055, -0.011]} scale={[0.57, 0.739, 0.57]} />
        <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.PaletteMaterial002} position={[0.221, 1.245, 0.012]} rotation={[0, 0, 0.223]} scale={0.868} />
      </group>
    </group>
  )
}

useGLTF.preload('/duck-transformed.glb')
